### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by moisesguimaraes** [boisgera/about#1]
Hi,

I'm trying to include **about** in a project that is GPLv2 / Commercial License. Can you guide me through the proper way to be compliant with your license?

https://github.com/moisesguimaraes/wolfcrypt-py

[ ]'s

**Comment by boisgera** [comment]
Hi Moisés,

The license is a basic MIT license, so as long as you include the project LICENSE.txt file contents in your source distribution (for example in your own LICENSE.rst file), GPL and commercial use of the software are fine.

Cheers,

SB
